---
openapi: 3.0.1
info:
  title: restingest-test
  description: restingest generic endpoints
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
  - url: /
x-pii-filter: ['title', 'date']
paths:
  /generics:
    post:
      summary: Store some data
      description: Store the posted data
      operationId: generic_post
      requestBody:
        description: A new document to be stored.
        content:
          application/json: {}
        required: true
      responses:
        200:
          description: Successful response.
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
